work/makeprocs.o: makeprocs.c ../../../include/lab2-api.h \
 ../../../include/usertraps.h ../../../include/misc.h \
 ../include/circular_buffer.h ../include/consumer.h
work/circular_buffer.o: circular_buffer.c ../include/circular_buffer.h
